.\" Copyright (c) 2026 Devin Teske <dteske@FreeBSD.org>
.\"
.\" SPDX-License-Identifier: BSD-2-Clause
.\"
.Dd October 7, 2026
.Dt AUTO-ROTATE-DISABLE 1
.Os
.Sh NAME
.Nm auto-rotate-disable
.Nd disable screen auto-rotation
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
turns screen auto-rotation off.
It runs
.Xr framework_autorotate 8
.Fl hold
and then
.Xr auto-rotate-osd 1
.Cm off .
.Xr auto-rotate-osd 1
draws the glyph with
.Xr bosd 1 .
.Pp
.Xr framework_autorotate 8
.Fl hold
creates
.Pa ~/.framework_hold_autorotate .
.Sh EXIT STATUS
.Nm
exits 0 after
.Fl hold .
It exits 1 when given an argument.
A usage message is printed on standard error.
It exits with the status of
.Nm framework_autorotate
when
.Fl hold
fails.
.Sh SEE ALSO
.Xr auto-rotate-enable 1 ,
.Xr auto-rotate-osd 1 ,
.Xr auto-rotate-toggle 1 ,
.Xr bhotkeys 1 ,
.Xr bosd 1 ,
.Xr framework_autorotate 8
.Sh AUTHORS
.An Devin Teske Aq Mt dteske@FreeBSD.org
